# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: danielt@alleninstitute.org
author_name: AICS
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: server
labextension_name: nbvv
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension for volume viewing
python_name: nbvv
repository: ''
test: false
viewer_name: ''

